### PR TITLE
Add a peers file for getting to know about each other, and other fun stuff.

### PR DESCRIPTION
**Pull request by scottcorgan**

### CODE REVIEW

**Comment by benhutton** [comment]
@scottcorgan are you aware that this repo is public?

**Comment by scottcorgan** [comment]
Ya. If that's a concern, I don't mind closing this. There's nothing on the doc I care about other people knowing outside DG.

**Comment by benhutton** [comment]
@scottcorgan yeah, it's not so much a privacy thing as a "given the intentionally public-facing nature of this repo, is this the right place to put this?" Or alternatively, do we still want this repo to be public facing?

@gaganawhad thoughts?

**Comment by scottcorgan** [comment]
Good point. This isn't necessarily information that's needed for a nice
team experience, so I'm open to closing this PR.

**Comment by benhutton** [comment]
@scottcorgan what would you think of a desiringgod/peers (or desiringgod.org/team) repo? It could host that org chart html file (maybe converted to markdown) that was posted in slack a while ago as the index and link out to files like this?

**Comment by scottcorgan** [comment]
Great idea :+1:

**Comment by gaganawhad** [comment]
@benhutton @scottcorgan I agree... a new repo might be a good place. Or how about a wiki page in www ? That might be easier to maintain.

**Comment by gaganawhad** [comment]
To add to the reasoning, a repo named `guides` isn't the right place for this, and we want our guides to be effective.

**Comment by scottcorgan** [comment]
I'd like to avoid wikis if possible because there's not history or PRs for changes available. Also, they're hidden and not really looked about by people.

With that said, I'll close this and we can open something new if we feel like it.

**Comment by gaganawhad** [comment]
hey @scottcorgan just a note ... I do like the idea. Wikis do have a revision history, and since it's not a repo, there won't be a need to add commits and review PRs etc. It's a lot less heavy. And in my opinion, repos that don't get attention can also tend to get hidden! :)

**Comment by benhutton** [comment]
@gaganawhad i don't hate the idea of a wiki, but i'm not a fan of attaching it to the www repo. This feels like it should be on an internal intranet or something.

**Pull request closed without merging**
