### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by pjmelling**
Clarify and simplify transfer of ownership details.

### CODE REVIEW

**Comment by pjmelling** [comment]
@joeosburn-desiringgod I've assigned this to you.

**Comment by joeosburn-desiringgod** [comment]
@pjmelling I think the language here is clear, but it seems as if we're losing some descriptive text that may be helpful. With the old text, we're communicating both a) The common types of ownership transfer and b) The fact that this should not be a common occurrence.

The new update, while well written, is almost so reductive that it has nearly removed all helpful information from the section.

**Comment by scottcorgan** [comment]
I think this should move forward or be closed (because of its age)

**Comment by pjmelling** [comment]
This is stale. I'm going to close this PR.

**Pull request closed without merging**
