### PR TITLE
Bring over client-side best practices

### PR DESCRIPTION
**Pull request by scottcorgan**
Ref https://github.com/desiringgod/www/issues/3195

---

 **Note:** It was migrated as is, there are changes to be made, but that can come later.

### CODE REVIEW

**Comment by scottcorgan** [comment]
@hchasey  For the sake of brevity, can I just delete all of the stale content and then add more content after the migration?

**Comment by hchasey** [comment]
@scottcorgan – yeah, let's delete the stale and see what we have let to work with. 

I think it also worth consider where in the guides this (parts or the whole) go is important as well before initially merging.

**Comment by scottcorgan** [comment]
@hchasey ok, I've removed some out of date content and have done some _small_ updates to other sections. This isn't exhaustive at all, but at least it's a start 👍

**Comment by scottcorgan** [comment]
@hchasey  But, now that I look at it, this seems like something to should go in `www`. Thoughts?

**Pull request closed without merging**
