### PR TITLE
Note bootstrap_staging as an optional step

### PR DESCRIPTION
**Pull request by gaganawhad**
Daily automated bootstrap on staging makes this step optional

### CODE REVIEW

**Comment by benhutton** [comment]
@gaganawhad I feel like this change is a bit simplistic. "Optional" isn't really the right word. "Not always necessary" is more accurate.

**Comment by gaganawhad** [comment]
@benhutton Can you explain further, why 'Optional' won't be the right word? And may be how I should update my changes? Some part of the reason to choose the word 'optional' is to maintain parity with other steps in this guide. Not sure if you are suggesting I update it to: 

```md
1. NOT ALWAYS NECESSARY: Bootstrap staging:
```

**Comment by benhutton** [comment]
@gaganawhad I hadn't thought about it in the context of the other "optional" lines...

How about you change "optional" to "if needed," in all 3 cases?

I think that gets more precisely to the sense of what we're looking for, right?

(To me "optional" implies at least some degree of "if you'd like to". I think with the exist 2 instances, the criteria for when its necessary are a little more subjective, or at least a little more vague. For this, it's actually quite clear: "If the staging database has been changed substantially since its last midnight bootstrap, bootstrap it again." Thus, I care more about this one. But you're right—I should care about all of them.)

**Comment by gaganawhad** [comment]
@benhutton Updated.

**Pull request merged**
